ligna = ("Moi je m'appelle 'Lolita'\n")
lignb = ("Lo ou bien Lola, du pareil au même\n")
lignc = ("Moi je m\'appelle \'Lolita\'\n")
lignd = ("Quand je rêve aux loups, c'est Lola qui saigne\n")
ligne = ("[...]\n")
lignf = ("C\'est pas ma faute\n")
ligng = ("Et quand je donne ma langue aux chats je vois les autres\n")
lignh = ("Tout prêts à se jeter sur moi, c'est pas ma faute à moi\n")
ligni = ("Si j\'entends tout autour de moi\n")
lignj = ("L.O.L.I.T.A, moi \'Lolita'\n")
print (ligna + lignb + lignc + lignd + ligne + lignf + ligng + lignh + lignj)
